In [1]:
import numpy as np

In [7]:
arr = np.array([[1,2,3],[5,6,7]])
arr

array([[1, 2, 3],
       [5, 6, 7]])

In [8]:
arr.ndim #prints the dimention of the array

2

In [9]:
arr.shape #size of the array

(2, 3)

In [10]:
arr.size #array size

6

In [12]:
arr.dtype #data type of array

dtype('int64')

In [13]:
arr.itemsize

8

In [15]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.empty((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [33]:
a = np.ones(5)
a+2

array([3., 3., 3., 3., 3.])

In [37]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]
             ])

b = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]
             ])

 

In [38]:
np.dot(a,b) #matrix multiplication

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [35]:
np.multiply(a,b) #Element wise multiplication

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [40]:
trans = np.dot(a,b)
trans = trans.T
trans

array([[ 30,  66, 102],
       [ 36,  81, 126],
       [ 42,  96, 150]])